# Generated by Django 6.0.4 on 2026-06-16 11:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Customer-facing code (stored uppercase).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed amount")],
                        default="percent",
                        max_length=16,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="If percentage: 0–100. If fixed: amount in shop currency.",
                        max_digits=12,
                    ),
                ),
                (
                    "min_order_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum cart subtotal before tax/shipping for this coupon to apply.",
                        max_digits=12,
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For percentage coupons: cap the discount (optional).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="If empty, valid immediately once active.",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, help_text="If empty, no end date.", null=True
                    ),
                ),
                (
                    "max_redemptions_total",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Global usage cap across all users (empty = unlimited).",
                        null=True,
                    ),
                ),
                (
                    "max_redemptions_per_user",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Per-user cap (empty = unlimited). Enforced at checkout.",
                        null=True,
                    ),
                ),
                (
                    "times_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Incremented when an order completes with this coupon (user flow).",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "ordering": ["-created_at"],
            },
        ),
    ]
