# Generated by Django 6.0.4 on 2026-06-29 06:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_paymentintent"),
        ("promotions", "0002_offer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default Referral Program", max_length=128
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "referee_discount_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed amount")],
                        default="percent",
                        max_length=16,
                    ),
                ),
                (
                    "referee_discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Referee welcome coupon: percent (0–100) or fixed amount.",
                        max_digits=12,
                    ),
                ),
                (
                    "referee_max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cap for percentage referee coupons (optional).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "referee_coupon_valid_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Days the referee coupon stays valid (empty = no expiry).",
                        null=True,
                    ),
                ),
                (
                    "referrer_reward_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("500.00"),
                        help_text="Wallet credit for referrer after referee's first paid order.",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Referral program",
                "verbose_name_plural": "Referral programs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="coupon",
            name="assigned_user",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, only this user may redeem the coupon (e.g. referral welcome offers).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_coupons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="min_order_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Minimum order total (subtotal + tax + shipping, before coupon) required for this coupon to apply.",
                max_digits=12,
            ),
        ),
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Shareable referral code (stored uppercase).",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Token for referral links (?ref=token).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral code",
                "verbose_name_plural": "Referral codes",
            },
        ),
        migrations.CreateModel(
            name="ReferralAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referrer_rewarded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "referee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_attribution",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referee_coupon",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_attribution",
                        to="promotions.coupon",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer_reward_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_rewards",
                        to="orders.order",
                    ),
                ),
                (
                    "referral_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attributions",
                        to="promotions.referralcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral attribution",
                "verbose_name_plural": "Referral attributions",
            },
        ),
    ]
