# Generated by Django 6.0.4 on 2026-07-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0003_referralprogram_coupon_assigned_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="offers/banners/"),
        ),
    ]
