# Generated by Django 6.0.4 on 2026-05-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("signup", "Signup"),
                    ("forgot_password", "Forgot Password"),
                    ("email_change", "Email Change"),
                ],
                default="signup",
                max_length=30,
            ),
        ),
    ]
