# Generated by Django 6.0.4 on 2026-05-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_otp_extra_data_otp_purpose"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_blocked",
        ),
        migrations.AlterField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("signup", "Signup"),
                    ("forgot_password", "Forgot Password"),
                    ("email_change", "Email Change"),
                ],
                max_length=30,
            ),
        ),
    ]
