# Generated by Django 6.0.4 on 2026-06-29 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_wallet_wallettransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid 10 digit phone number",
                        regex="^[6-9]\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="reason",
            field=models.CharField(
                choices=[
                    ("order_cancel", "Order cancellation"),
                    ("return_refund", "Return refund"),
                    ("order_payment", "Order payment"),
                    ("referral_reward", "Referral reward"),
                    ("admin_adjustment", "Admin adjustment"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=32,
            ),
        ),
    ]
