# Generated by Django 6.0.4 on 2026-07-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofilenumber"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfileNumber",
        ),
    ]
