# Generated by Django 6.0.4 on 2026-05-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_productvariant_variantimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variantimage",
            options={"ordering": ["display_order", "-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="material",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="variant_name",
            field=models.CharField(default="Default Variant", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="variantimage",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="variantimage",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["sku"], name="catalog_pro_sku_187601_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["is_active"], name="catalog_pro_is_acti_ce92a3_idx"
            ),
        ),
    ]
