# Generated by Django 6.0.4 on 2026-05-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_roomtype_product_room_types"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)), name="variant_price_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock__gte", 0)), name="variant_stock_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="variantimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("variant",),
                name="unique_primary_image_per_variant",
            ),
        ),
    ]
