# Generated by Django 6.0.4 on 2026-05-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productvariant_variant_price_gt_0_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantimage",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantimage",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variantimage",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
