# Generated by Django 6.0.4 on 2026-05-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_variantimage_file_size_variantimage_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
