# Generated by Django 6.0.4 on 2026-06-20 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderline_fulfillment_status_alter_order_status_and_more"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="applied_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="promotions.coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Snapshot of coupon code at checkout time.",
                max_length=64,
            ),
        ),
    ]
