# Generated by Django 6.0.4 on 2026-07-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_paymentintent"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="cancelled_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderline",
            name="returned_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
